### ISSUE TITLE
Support for alternate servers & authentication

### ISSUE THREAD

**Issue by cyqsimon** [lucas-bortoli/ntfysh-windows#1]
See [here](https://ntfy.sh/docs/config/#example-private-instance) and [here](https://ntfy.sh/docs/subscribe/api/#authentication).

It makes this application usable with private self-hosted instances.

**Comment by alexhorner** [comment]
@cyqsimon 

I have basically implemented this now. It is not perfect and still needs more work, and I have some stuff to finish off tomorrow at minimum for the PR to be ready, but if you want a little look at what I've done (screenshots) take a look at #2 

Thanks @lucas-bortoli for making this project, I have learned a fair bit about WinForms as a result, and I hope you'll like the PR!
