### ISSUE TITLE
Reconnecting

### ISSUE THREAD

**Issue by er1z** [lucas-bortoli/ntfysh-windows#10]
Can you add a support to reconnect the ntfy server if connection drops/server was killed?

**Comment by alexhorner** [comment]
I believe the reason I did not do this was because it would require a fair restructure of how listener threads were started up. Just going off memory though, I'll look a little later

**Comment by alexhorner** [comment]
I have checked this and we do attempt a reconnect once every 3 seconds, for a maximum of 10 attempts (30 seconds). After a sucessful connection, the attempts are reset back to 0 so upon the next disconnection, it will once again make 10 more attempts.

**Comment by er1z** [comment]
Once I restarted ntfy, no notifications were received anymore. But may be this is due to the fact that I started it after 30 seconds. How about allowing to customize this period?

**Comment by alexhorner** [comment]
> Once I restarted ntfy, no notifications were received anymore. But may be this is due to the fact that I started it after 30 seconds. How about allowing to customize this period?

This 30 seconds is split into two numbers, 3 second wait at 10 attempts. We could probably expose these as options?

**Comment by er1z** [comment]
That may work out.

**Comment by alexhorner** [comment]
Hi @er1z 

Please see PR #11 for the updates based on this conversation. They allow you to adjust the values.

Please also note that after all attempts have been exhausted, you will get an error popup for each topic. This happened already, so you should have seen this in your previous test.
